### ISSUE TITLE
Error when loading OXE data with the example code

### ISSUE THREAD

**Issue by MasterXiong** [octo-models/octo#128]
Hi, 

Thanks for open-sourcing the brilliant Octo code! I'm trying to run the [example code](https://github.com/octo-models/octo/blob/main/examples/05_dataloading.ipynb) on OXE data loading, but got the following error: 
```
Traceback (most recent call last):
  File "/user/fine-tune/tools/dataloader.py", line 13, in <module>
    dataset = make_single_dataset(dataset_kwargs, train=True) # load the train split
  File "/user/fine-tune/3v2OctoFineTuning/SimplerEnv/octo/octo/data/dataset.py", line 436, in make_single_dataset
    dataset, dataset_statistics = make_dataset_from_rlds(
  File "/user/fine-tune/3v2OctoFineTuning/SimplerEnv/octo/octo/data/dataset.py", line 364, in make_dataset_from_rlds
    builder = tfds.builder(name, data_dir=data_dir)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py", line 168, in __call__
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/load.py", line 219, in builder
    with py_utils.try_reraise(
  File "/opt/conda/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 418, in try_reraise
    reraise(e, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 385, in reraise
    raise exception from e
FileNotFoundError: Failed to construct dataset "austin_buds_dataset_converted_externally_to_rlds", builder_kwargs "{'data_dir': 'gs://gresearch/robotics'}": Could not load da
taset info from austin_buds_dataset_converted_externally_to_rlds/0.1.0/dataset_info.json
```
Could you help have a look at what is the issue here? Thanks!

**Comment by MasterXiong** [comment]
Problem solved. Seems to be an issue with `tfds` version. 

[link](https://github.com/google-deepmind/open_x_embodiment/issues/29#issuecomment-1866622893)
